M48
; DRILL file {KiCad 8.0.5} date 2024-11-30T19:19:10-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-30T19:19:10-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X3.493Y-1.5506
X3.5717Y-5.3774
X8.7774Y-1.6294
X8.7774Y-5.3774
M30
